import path from "node:path";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";
import pg from "pg";

const { Pool } = pg;
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.resolve(process.env.SOURCE_SQLITE_PATH || path.join(root, "data", "boms.sqlite"));
const connectionString = process.env.DATABASE_URL;

function quoteIdentifier(identifier) {
  return `"${String(identifier).replaceAll('"', '""')}"`;
}

function postgresType(sqliteType) {
  const type = String(sqliteType || "").toUpperCase();
  if (type.includes("INT")) return "BIGINT";
  if (type.includes("REAL") || type.includes("FLOA") || type.includes("DOUB")) return "DOUBLE PRECISION";
  if (type.includes("BLOB")) return "BYTEA";
  if (type.includes("NUMERIC") || type.includes("DECIMAL")) return type;
  if (type.includes("BOOL")) return "BOOLEAN";
  return "TEXT";
}

function postgresDefault(value) {
  if (value == null) return "";
  const trimmed = String(value).trim();
  if (/^\(?\s*datetime\s*\(\s*'now'\s*\)\s*\)?$/i.test(trimmed)) return " DEFAULT CURRENT_TIMESTAMP";
  if (/^\(?\s*date\s*\(\s*'now'\s*\)\s*\)?$/i.test(trimmed)) return " DEFAULT CURRENT_DATE";
  return ` DEFAULT ${trimmed.replace(/^\((.*)\)$/s, "$1")}`;
}

function buildCreateTable(table, columns, sourceDdl) {
  const primaryKey = columns.filter((column) => column.pk).sort((left, right) => left.pk - right.pk);
  const definitions = columns.map((column) => {
    const identity = /AUTOINCREMENT/i.test(sourceDdl) && column.pk ? " GENERATED BY DEFAULT AS IDENTITY" : "";
    const notNull = column.notnull && !column.pk ? " NOT NULL" : "";
    return `${quoteIdentifier(column.name)} ${postgresType(column.type)}${identity}${notNull}${postgresDefault(column.dflt_value)}`;
  });
  if (primaryKey.length) definitions.push(`PRIMARY KEY (${primaryKey.map((column) => quoteIdentifier(column.name)).join(", ")})`);
  return `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(table)} (${definitions.join(", ")})`;
}

async function createForeignKeys(sqlite, pool, table) {
  const foreignKeys = sqlite.pragma(`foreign_key_list(${JSON.stringify(table)})`);
  const groups = new Map();
  for (const key of foreignKeys) {
    const group = groups.get(key.id) || [];
    group.push(key);
    groups.set(key.id, group);
  }
  for (const [id, group] of groups) {
    group.sort((left, right) => left.seq - right.seq);
    const name = `migrated_${table}_${id}`.slice(0, 60);
    const exists = await pool.query("SELECT 1 FROM pg_constraint WHERE conname = $1", [name]);
    if (exists.rowCount) continue;
    const sourceColumns = group.map((key) => quoteIdentifier(key.from)).join(", ");
    const targetColumns = group.map((key) => quoteIdentifier(key.to)).join(", ");
    const updateAction = group[0].on_update && group[0].on_update !== "NO ACTION" ? ` ON UPDATE ${group[0].on_update}` : "";
    const deleteAction = group[0].on_delete && group[0].on_delete !== "NO ACTION" ? ` ON DELETE ${group[0].on_delete}` : "";
    await pool.query(`ALTER TABLE ${quoteIdentifier(table)} ADD CONSTRAINT ${quoteIdentifier(name)} FOREIGN KEY (${sourceColumns}) REFERENCES ${quoteIdentifier(group[0].table)} (${targetColumns})${updateAction}${deleteAction}`);
  }
}

async function createUniqueIndexes(sqlite, pool, table) {
  for (const index of sqlite.pragma(`index_list(${JSON.stringify(table)})`)) {
    if (!index.unique || index.origin === "pk" || index.partial) continue;
    const columns = sqlite.pragma(`index_info(${JSON.stringify(index.name)})`)
      .map((column) => column.name)
      .filter(Boolean);
    if (!columns.length) continue;
    const name = `migrated_unique_${table}_${index.seq}`.slice(0, 60);
    await pool.query(`CREATE UNIQUE INDEX ${quoteIdentifier(name)} ON ${quoteIdentifier(table)} (${columns.map(quoteIdentifier).join(", ")})`);
  }
}

async function copyTable(sqlite, pool, table) {
  const columns = sqlite.pragma(`table_info(${JSON.stringify(table)})`);
  const names = columns.map((column) => column.name);
  const quotedNames = names.map(quoteIdentifier).join(", ");
  const rows = sqlite.prepare(`SELECT * FROM ${quoteIdentifier(table)}`).iterate();
  const batchSize = 100;
  let batch = [];
  let imported = 0;

  async function insertBatch() {
    if (!batch.length) return;
    const values = [];
    const placeholders = batch.map((row) => `(${row.map((value) => {
      values.push(value);
      return `$${values.length}`;
    }).join(", ")})`).join(", ");
    await pool.query(`INSERT INTO ${quoteIdentifier(table)} (${quotedNames}) VALUES ${placeholders} ON CONFLICT DO NOTHING`, values);
    imported += batch.length;
    batch = [];
  }

  for (const row of rows) {
    batch.push(names.map((name) => row[name]));
    if (batch.length >= batchSize) await insertBatch();
  }
  await insertBatch();
  return imported;
}

async function main() {
  if (!connectionString) throw new Error("Set DATABASE_URL in the shell before importing to Postgres.");
  const sqlite = new Database(sourcePath, { readonly: true, fileMustExist: true });
  const pool = new Pool({ connectionString, max: 1, connectionTimeoutMillis: 10_000 });

  try {
    const tables = sqlite.prepare("SELECT name, sql FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
    const targetTables = await pool.query("SELECT tablename FROM pg_tables WHERE schemaname = 'public'");
    if (targetTables.rows.length) {
      throw new Error("The target Postgres public schema is not empty. Use a fresh Supabase project to avoid mixing data.");
    }

    for (const table of tables) {
      const columns = sqlite.pragma(`table_info(${JSON.stringify(table.name)})`);
      await pool.query(buildCreateTable(table.name, columns, table.sql || ""));
    }
    for (const table of tables) {
      const count = await copyTable(sqlite, pool, table.name);
      console.log(`Imported ${table.name}: ${count} rows`);
    }
    for (const table of tables) await createForeignKeys(sqlite, pool, table.name);
    for (const table of tables) await createUniqueIndexes(sqlite, pool, table.name);

    const indexes = sqlite.prepare("SELECT sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL").all();
    for (const index of indexes) {
      const sql = index.sql.replace(/^CREATE\s+(UNIQUE\s+)?INDEX\s+/i, (statement) => `${statement.toUpperCase().includes("UNIQUE") ? "CREATE UNIQUE INDEX IF NOT EXISTS " : "CREATE INDEX IF NOT EXISTS "}`);
      await pool.query(sql);
    }
    await pool.query(`
      CREATE OR REPLACE FUNCTION prevent_audit_log_mutation()
      RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        RAISE EXCEPTION 'audit log records are append-only';
      END;
      $$
    `);
    await pool.query(`
      CREATE TRIGGER audit_logs_append_only
      BEFORE UPDATE OR DELETE ON audit_logs
      FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation()
    `);
    console.log(`Imported ${tables.length} tables into Postgres.`);
  } finally {
    sqlite.close();
    await pool.end();
  }
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});